"""Add content and tags tables with relationships

Revision ID: 0fdc5f98078d
Revises: 76d248d9a323
Create Date: 2024-11-13 20:18:09.463036

"""

from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "0fdc5f98078d"
down_revision: Union[str, None] = "76d248d9a323"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
