"""Add content_tags association table

Revision ID: 24a4b0390dd8
Revises: 0fdc5f98078d
Create Date: 2024-11-13 20:23:09.778710

"""

from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "24a4b0390dd8"
down_revision: Union[str, None] = "0fdc5f98078d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
