"""add content_versions table

Revision ID: 3a7b0b241cb5
Revises: 0a1bf46b926d
Create Date: 2025-04-11 16:49:39.541577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3a7b0b241cb5"
down_revision: Union[str, None] = "0a1bf46b926d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "content", sa.Column("publish_date", sa.DateTime(), nullable=True)
    )
    op.drop_column("content", "publish_at")
    op.add_column(
        "content_versions", sa.Column("meta_title", sa.Text(), nullable=True)
    )
    op.add_column(
        "content_versions",
        sa.Column("meta_description", sa.Text(), nullable=True),
    )
    op.add_column(
        "content_versions",
        sa.Column("meta_keywords", sa.Text(), nullable=True),
    )
    op.add_column(
        "content_versions", sa.Column("status", sa.String(), nullable=False)
    )
    op.add_column(
        "content_versions", sa.Column("author_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "content_versions",
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "content_versions",
        "users",
        ["author_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "content_versions", type_="foreignkey")
    op.drop_column("content_versions", "created_at")
    op.drop_column("content_versions", "author_id")
    op.drop_column("content_versions", "status")
    op.drop_column("content_versions", "meta_keywords")
    op.drop_column("content_versions", "meta_description")
    op.drop_column("content_versions", "meta_title")
    op.add_column(
        "content",
        sa.Column(
            "publish_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("content", "publish_date")
    # ### end Alembic commands ###
