"""Fix content relationships and add content_tags table

Revision ID: d4aa2f33fb76
Revises: b3a04d058e56
Create Date: 2024-11-15 16:33:51.057020

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4aa2f33fb76"
down_revision: Union[str, None] = "b3a04d058e56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("target_user_id", sa.Integer(), nullable=True),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_logs_id"), "activity_logs", ["id"], unique=False)
    op.alter_column(
        "content",
        "status",
        existing_type=postgresql.ENUM("DRAFT", "PENDING", "PUBLISHED", name="contentstatus"),
        nullable=False,
    )
    op.alter_column("content", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("content", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("content", "author_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("content", "author_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("content", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("content", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column(
        "content",
        "status",
        existing_type=postgresql.ENUM("DRAFT", "PENDING", "PUBLISHED", name="contentstatus"),
        nullable=True,
    )
    op.drop_index(op.f("ix_activity_logs_id"), table_name="activity_logs")
    op.drop_table("activity_logs")
    # ### end Alembic commands ###
